footer:
    since: 2024
    icon:
        name: fa fa-code
        animated: false
        color: "#808080"
    powered: false

scheme: Gemini

menu:
    home: / || fa fa-home
    archives: /archives/ || fa fa-archive
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    about: /about/ || fa fa-user

sidebar:
    position: left
    display: post
    padding: 18
    offsetTop: 12

social:
    GitHub: https://github.com/ZF-Clark || fab fa-github

social_icons:
    enable: true
    icons_only: false
    transition: false

avatar:
    url: /images/avatar.png
    rounded: true
    rotated: false

codeblock:
    theme:
        light: default
        dark: stackoverflow-dark
    copy_button:
        enable: true
        show_result: true
        style: flat

back2top:
    enable: true
    sidebar: false
    scrollpercent: true

reading_progress:
    enable: true
    position: top
    color: "#373E50"
    height: 3px

bookmark:
    enable: false
    color: "#222"
    save: auto

github_banner:
    enable: true
    permalink: https://github.com/ZF-Clark
    title: Follow me on GitHub

font:
    enable: true
    host: https://fonts.googleapis.com
    global:
        external: true
        family: Lato
        size: 1
    title:
        external: true
        family: Lato
        size: 1.5
    codes:
        external: true
        family: consolas

seo: true
index_with_subtitle: true

local_search:
    enable: true
    trigger: auto
    top_n_per_article: 1
    unescape: false
    preload: false

post_meta:
    item_text: true
    created_at: true
    updated_at:
        enable: true
        another_day: true
    categories: true

post_wordcount:
    item_text: true
    wordcount: true
    min2read: true
    totalwordcount: false

symbols_count_time:
    separated_meta: true
    item_text_total: false

pjax: true

fancybox: true

mediumzoom: true

lazyload: true

pangu: true

comments:
    active: false

math:
    every_page: false
    mathjax:
        enable: false
    katex:
        enable: false

mermaid:
    enable: true
    theme:
        light: default
        dark: dark

custom_logo:
    enabled: false

custom_file_path:
    style: source/_data/styles.styl
